name: Trigger auto deployment for asdfasdcasdfasf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/asdfasdcasdfasf-AutoDeployTrigger-fbe5d60e-b462-4dad-a0bf-cd0c7271d18a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASDFASDCASDFASF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASDFASDCASDFASF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASDFASDCASDFASF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.ASDFASDCASDFASF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASDFASDCASDFASF_REGISTRY_PASSWORD }}
          containerAppName: asdfasdcasdfasf
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/asdfasdcasdfasf:${{ github.sha }}
          dockerfilePath: Dockerfile


