name: Trigger auto deployment for tmtestnewrepo123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tmtestnewrepo123-AutoDeployTrigger-5ac9bc74-2c6a-47be-9604-b94e8243ab02.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTNEWREPO123_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTNEWREPO123_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTNEWREPO123_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.TMTESTNEWREPO123_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTNEWREPO123_REGISTRY_PASSWORD }}
          containerAppName: tmtestnewrepo123
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/tmtestnewrepo123:${{ github.sha }}
          


