name: Trigger auto deployment for tmtest-docker-python-wlp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tmtest-docker-python-wlp-AutoDeployTrigger-ef432895-091f-4435-b0d0-ed660c00dcdc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTDOCKERPYTHONWLP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTDOCKERPYTHONWLP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTDOCKERPYTHONWLP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: index.docker.io
          registryUsername: ${{ secrets.TMTESTDOCKERPYTHONWLP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTDOCKERPYTHONWLP_REGISTRY_PASSWORD }}
          containerAppName: tmtest-docker-python-wlp
          resourceGroup: tmauldin-test
          imageToBuild: index.docker.io/tmtest-docker-python-wlp:${{ github.sha }}
          


